providers:
  deepseek:
    api_key_env: "DEEPSEEK_API_KEY" 
    base_url: "https://api.deepseek.com"
    models:
      "deepseek-chat": "非推理模型,LLM"
      "deepseek-reasoner": "推理模型,LLM"
  
  qwen:
    api_key_env: "UNIFIED_API_KEY"
    base_url: "https://api.agicto.cn/v1"
    models: 
      "qwen3-vl-plus": "闭源混合推理模型, 百万token价格: in:1 out:10"
      "qwen3-vl-235b-a22b-instruct": "非思考模型, MLLM, 百万token价格: in:2 out:8"
      "qwen3-vl-235b-a22b-thinking": "思考模型, MLLM, 百万token价格: in:2 out:20"

  openai:
    api_key_env: "UNIFIED_API_KEY"
    base_url: "https://api.agicto.cn/v1"
    # api_key_env: "OPENAI_API_KEY"
    # base_url: "https://api.openai.com/v1"
    models:
      "gpt-5.2": "混合推理模型, MLLM, 不会输出思维链具体内容。百万token价格: in:12.25 out:98"
      "gpt-5.1": "混合推理模型, MLLM, 不会输出思维链具体内容。百万token价格: in:8.75 out:70"
      "gpt-5": "混合推理模型, MLLM, 百万token价格: in:8.75 out:70"

  google:
    api_key_env: "UNIFIED_API_KEY"
    base_url: "https://api.agicto.cn/v1"  
    # api_key_env: "GEMINI_API_KEY"
    # base_url: "https://generativelanguage.googleapis.com/v1beta/openai/"
    models:
      "gemini-3-pro-preview": "多模态理解模型, 百万token价格: in:14 out:84"
      "gemini-3-flash-preview": "多模态理解模型, 百万token价格: in:3.5 out:21" 
